// Hebrew names of perfume notes. Keys are the English names in lower case, exactly as they
// are stored in the database. A note that is missing here is simply shown in English, so the
// list can grow over time (scripts/notes-report.mjs lists the notes that are still missing).
export const NOTES_HE: Record<string, string> = {
  // citrus
  'bergamot': 'ברגמוט',
  'lemon': 'לימון',
  'orange': 'תפוז',
  'mandarin orange': 'מנדרינה',
  'mandarin': 'מנדרינה',
  'tangerine': 'טנג׳רין',
  'grapefruit': 'אשכולית',
  'pink grapefruit': 'אשכולית ורודה',
  'lime': 'ליים',
  'yuzu': 'יוזו',
  'blood orange': 'תפוז דם',
  'bitter orange': 'תפוז מר',
  'bigarade': 'תפוז מר',
  'neroli': 'נרולי',
  'orange blossom': 'פריחת תפוז',
  'petitgrain': 'פטיגרין',
  'citron': 'ציטרון',
  'kumquat': 'קומקוואט',
  'lemon verbena': 'ורבנה לימונית',
  'lemongrass': 'עשב לימון',
  'citruses': 'הדרים',
  'citrus': 'הדרים',
  // fruits
  'apple': 'תפוח',
  'green apple': 'תפוח ירוק',
  'pear': 'אגס',
  'peach': 'אפרסק',
  'apricot': 'משמש',
  'plum': 'שזיף',
  'cherry': 'דובדבן',
  'black cherry': 'דובדבן שחור',
  'cherry liqueur': 'ליקר דובדבנים',
  'sour cherry': 'דובדבן חמוץ',
  'strawberry': 'תות שדה',
  'raspberry': 'פטל',
  'blackberry': 'פטל שחור',
  'blueberry': 'אוכמניות',
  'black currant': 'דומדמניות שחורות',
  'red currant': 'דומדמניות אדומות',
  'cassis': 'קסיס',
  'pineapple': 'אננס',
  'mango': 'מנגו',
  'coconut': 'קוקוס',
  'banana': 'בננה',
  'fig': 'תאנה',
  'melon': 'מלון',
  'watermelon': 'אבטיח',
  'pomegranate': 'רימון',
  'litchi': 'ליצ׳י',
  'lychee': 'ליצ׳י',
  'passionfruit': 'פסיפלורה',
  'passion fruit': 'פסיפלורה',
  'papaya': 'פפאיה',
  'guava': 'גויאבה',
  'grape': 'ענבים',
  'cranberry': 'חמוציות',
  'date': 'תמר',
  'dried fruits': 'פירות יבשים',
  'fruity notes': 'תווי פירות',
  'tropical fruits': 'פירות טרופיים',
  'quince': 'חבוש',
  'nectarine': 'נקטרינה',
  'rhubarb': 'ריבס',
  'cantaloupe': 'מלון קנטלופ',
  'berries': 'פירות יער',
  'wild berries': 'פירות יער',
  'red berries': 'פירות יער אדומים',
  'currant': 'דומדמניות',
  'prickly pear': 'צבר',
  // flowers
  'rose': 'ורד',
  'turkish rose': 'ורד טורקי',
  'bulgarian rose': 'ורד בולגרי',
  'damask rose': 'ורד דמשקאי',
  'may rose': 'ורד מאי',
  'tea rose': 'ורד תה',
  'rose petals': 'עלי כותרת של ורד',
  'jasmine': 'יסמין',
  'jasmine sambac': 'יסמין סמבק',
  'tuberose': 'טוברוז',
  'ylang-ylang': 'איילנג-איילנג',
  'ylang ylang': 'איילנג-איילנג',
  'lily-of-the-valley': 'שושן עמקים',
  'lily of the valley': 'שושן עמקים',
  'lily': 'שושנה',
  'peony': 'אדמונית',
  'violet': 'סיגלית',
  'violet leaf': 'עלה סיגלית',
  'iris': 'איריס',
  'orris root': 'שורש איריס',
  'orchid': 'סחלב',
  'gardenia': 'גרדניה',
  'magnolia': 'מגנוליה',
  'freesia': 'פרזיה',
  'lavender': 'לבנדר',
  'geranium': 'גרניום',
  'carnation': 'ציפורן (פרח)',
  'heliotrope': 'הליוטרופ',
  'mimosa': 'מימוזה',
  'cyclamen': 'רקפת',
  'lotus': 'לוטוס',
  'water lily': 'נופר',
  'frangipani': 'פרנג׳יפני',
  'osmanthus': 'אוסמנטוס',
  'hyacinth': 'יקינתון',
  'narcissus': 'נרקיס',
  'honeysuckle': 'יערה',
  'wisteria': 'ויסטריה',
  'chamomile': 'קמומיל',
  'cherry blossom': 'פריחת דובדבן',
  'apple blossom': 'פריחת תפוח',
  'white flowers': 'פרחים לבנים',
  'white floral': 'פרחים לבנים',
  'floral notes': 'תווי פרחים',
  'tiare flower': 'פרח טיארה',
  'hibiscus': 'היביסקוס',
  'camellia': 'קמליה',
  'lilac': 'לילך',
  'poppy': 'פרג',
  'rose oil': 'שמן ורדים',
  'jasmine tea': 'תה יסמין',
  'petalia': 'פטליה',
  'hedione': 'הדיון',
  'sweet pea': 'אפונה ריחנית',
  'plumeria': 'פלומריה',
  'linden blossom': 'פריחת טיליה',
  'linden': 'טיליה',
  'tagetes': 'ציפורני חתול',
  'marigold': 'ציפורני חתול',
  'daffodil': 'נרקיס צהוב',
  'lily-of-the-valley (muguet)': 'שושן עמקים',
  // spices
  'pink pepper': 'פלפל ורוד',
  'black pepper': 'פלפל שחור',
  'pepper': 'פלפל',
  'white pepper': 'פלפל לבן',
  'sichuan pepper': 'פלפל סצ׳ואן',
  'cardamom': 'הל',
  'cinnamon': 'קינמון',
  'cloves': 'ציפורן (תבלין)',
  'clove': 'ציפורן (תבלין)',
  'nutmeg': 'אגוז מוסקט',
  'ginger': 'ג׳ינג׳ר',
  'saffron': 'זעפרן',
  'cumin': 'כמון',
  'coriander': 'כוסברה',
  'star anise': 'אניס כוכבי',
  'anise': 'אניס',
  'allspice': 'פלפל אנגלי',
  'turmeric': 'כורכום',
  'chili pepper': 'פלפל צ׳ילי',
  'paprika': 'פפריקה',
  'juniper berries': 'גרגרי ערער',
  'juniper': 'ערער',
  'caraway': 'קימל',
  'fennel': 'שומר',
  'spicy notes': 'תווים חריפים',
  'warm spicy notes': 'תווי תבלין חמים',
  'fresh spicy notes': 'תווי תבלין רעננים',
  'mace': 'מקל אגוז מוסקט',
  // woods
  'sandalwood': 'סנדל',
  'cedar': 'ארז',
  'cedarwood': 'עץ ארז',
  'vetiver': 'ווטיבר',
  'patchouli': 'פצ׳ולי',
  'agarwood (oud)': 'עוּד (אגרווד)',
  'oud': 'עוּד',
  'agarwood': 'עוּד (אגרווד)',
  'guaiac wood': 'עץ גואיאק',
  'cypress': 'ברוש',
  'pine': 'אורן',
  'pine tree': 'אורן',
  'birch': 'ליבנה',
  'oak': 'אלון',
  'oakmoss': 'טחב אלון',
  'oak moss': 'טחב אלון',
  'rosewood': 'עץ ורד',
  'brazilian rosewood': 'עץ ורד ברזילאי',
  'teak': 'טיק',
  'bamboo': 'במבוק',
  'driftwood': 'עץ סחף',
  'papyrus': 'פפירוס',
  'palo santo': 'פאלו סנטו',
  'cashmeran': 'קשמרן',
  'amberwood': 'עץ ענבר',
  'woody notes': 'תווי עץ',
  'sandal': 'סנדל',
  'hinoki': 'היינוקי',
  'ebony': 'הובנה',
  'balsam fir': 'אשוח בלסמי',
  'moss': 'טחב',
  'tree moss': 'טחב עצים',
  // resins and balsams
  'amber': 'ענבר',
  'ambergris': 'ענבר אפור',
  'labdanum': 'לבדנום',
  'benzoin': 'בנזואין',
  'incense': 'קטורת',
  'olibanum': 'לבונה',
  'frankincense': 'לבונה',
  'myrrh': 'מור',
  'elemi': 'אלמי',
  'opoponax': 'אופופונקס',
  'peru balsam': 'בלסם פרו',
  'tolu balsam': 'בלסם טולו',
  'balsam': 'בלסם',
  'styrax': 'סטירקס',
  'resin': 'שרף',
  'fir resin': 'שרף אשוח',
  'fir': 'אשוח',
  'copal': 'קופל',
  'galbanum': 'גלבנום',
  'balsamic notes': 'תווים בלסמיים',
  // sweet and gourmand
  'vanilla': 'וניל',
  'tonka bean': 'פול טונקה',
  'caramel': 'קרמל',
  'honey': 'דבש',
  'chocolate': 'שוקולד',
  'dark chocolate': 'שוקולד מריר',
  'cacao': 'קקאו',
  'cocoa': 'קקאו',
  'coffee': 'קפה',
  'almond': 'שקד',
  'bitter almond': 'שקד מר',
  'praline': 'פרלין',
  'sugar': 'סוכר',
  'cotton candy': 'צמר גפן מתוק',
  'milk': 'חלב',
  'cream': 'שמנת',
  'butter': 'חמאה',
  'marshmallow': 'מרשמלו',
  'rum': 'רום',
  'whiskey': 'ויסקי',
  'cognac': 'קוניאק',
  'brandy': 'ברנדי',
  'champagne': 'שמפניה',
  'wine': 'יין',
  'tea': 'תה',
  'black tea': 'תה שחור',
  'green tea': 'תה ירוק',
  'tobacco': 'טבק',
  'tobacco leaf': 'עלה טבק',
  'tobacco blossom': 'פריחת טבק',
  'pistachio': 'פיסטוק',
  'hazelnut': 'אגוז לוז',
  'walnut': 'אגוז מלך',
  'chestnut': 'ערמון',
  'maple syrup': 'סירופ מייפל',
  'licorice': 'ליקריץ',
  'coconut milk': 'חלב קוקוס',
  'popcorn': 'פופקורן',
  'candy': 'ממתקים',
  'toffee': 'טופי',
  'cookie': 'עוגיה',
  'biscuit': 'ביסקוויט',
  'brown sugar': 'סוכר חום',
  'sweet notes': 'תווים מתוקים',
  'cinnamon roll': 'סינבון',
  'bourbon': 'בורבון',
  'bourbon vanilla': 'וניל בורבון',
  'dried fruit': 'פירות יבשים',
  // musks and molecules
  'musk': 'מושק',
  'white musk': 'מושק לבן',
  'ambroxan': 'אמברוקסן',
  'iso e super': 'איזו אי סופר',
  'coumarin': 'קומרין',
  'aldehydes': 'אלדהידים',
  'ambermax™': 'אמברמקס',
  'ambermax': 'אמברמקס',
  'calone': 'קלון',
  'salicylates': 'סליצילטים',
  'ambrette': 'אמברט',
  'powdery notes': 'תווי אבקה',
  'sugar cane': 'קנה סוכר',
  // herbs, green and fresh
  'mint': 'נענע',
  'peppermint': 'נענע חריפה',
  'spearmint': 'נענע ירוקה',
  'basil': 'בזיליקום',
  'sage': 'מרווה',
  'clary sage': 'מרווה סקלארי',
  'rosemary': 'רוזמרין',
  'thyme': 'טימין',
  'tarragon': 'טרגון',
  'green notes': 'תווים ירוקים',
  'grass': 'דשא',
  'leaves': 'עלים',
  'green leaves': 'עלים ירוקים',
  'fig leaf': 'עלה תאנה',
  'bay leaf': 'עלה דפנה',
  'eucalyptus': 'אקליפטוס',
  'artemisia': 'לענה',
  'wormwood': 'לענה',
  'oregano': 'אורגנו',
  'parsley': 'פטרוזיליה',
  'cucumber': 'מלפפון',
  'celery': 'סלרי',
  'tomato leaf': 'עלה עגבנייה',
  'angelica': 'אנג׳ליקה',
  'hay': 'חציר',
  'aromatic notes': 'תווים ארומטיים',
  'herbal notes': 'תווי עשבי תיבול',
  'herbs': 'עשבי תיבול',
  'fresh notes': 'תווים רעננים',
  'lavandin': 'לוונדין',
  'cannabis': 'קנאביס',
  'ivy': 'קיסוס',
  // leather, smoke, animal
  'leather': 'עור',
  'suede': 'זמש',
  'birch tar': 'זפת ליבנה',
  'smoke': 'עשן',
  'smoky notes': 'תווי עשן',
  'castoreum': 'קסטוריאום',
  'civet': 'זבדה',
  'beeswax': 'שעוות דבורים',
  'wax': 'שעווה',
  'animalic notes': 'תווים חייתיים',
  'incense smoke': 'עשן קטורת',
  'tar': 'זפת',
  'burnt notes': 'תווים שרופים',
  // sea, mineral, earth
  'sea notes': 'תווי ים',
  'marine notes': 'תווי ים',
  'sea salt': 'מלח ים',
  'salt': 'מלח',
  'water notes': 'תווי מים',
  'ozonic notes': 'תווי אוזון',
  'metallic notes': 'תווי מתכת',
  'mineral notes': 'תווים מינרליים',
  'rain': 'גשם',
  'earthy notes': 'תווי אדמה',
  'soil': 'אדמה',
  'earth': 'אדמה',
  'sand': 'חול',
  'stone': 'אבן',
  'ice': 'קרח',
  'aquatic notes': 'תווים ימיים',
  // other
  'cotton': 'כותנה',
  'soap': 'סבון',
  'linen': 'פשתן',
  'paper': 'נייר',
  'rubber': 'גומי',
  'gasoline': 'בנזין',
  'plastic': 'פלסטיק',
  'aldehyde': 'אלדהיד',
  'clean notes': 'תווי ניקיון',
  'cedar leaf': 'עלה ארז',
  'myrtle': 'הדס',
  'african orange flower': 'פרח תפוז אפריקאי',
  'pitosporum': 'פיטוספורום',
  'ambrette (musk mallow)': 'אמברט (חלמית מושק)',
  'vervain': 'ורבנה',
  'siam benzoin': 'בנזואין סיאמי',
  'pepperwood™': 'פפרווד',
  'cypriol oil or nagarmotha': 'שמן סיפריול (נגרמוטה)',
  'pine needles': 'מחטי אורן',
  'buchu or agathosma': 'בוצ׳ו (אגתוסמה)',
  'virginia cedar': 'ארז וירג׳יני',
  'candied almond': 'שקד מסוכר',
  'cashmere wood': 'עץ קשמיר',
  'blood mandarin': 'מנדרינה דם',
  'oriental notes': 'תווים מזרחיים',
  'woodsy notes': 'תווי עץ',
  'pelargonium': 'פלרגוניום',
  'flint': 'צור',
  'neroli essence': 'תמצית נרולי',
  'davana': 'דבנה',
  'indonesian patchouli leaf': 'עלה פצ׳ולי אינדונזי',
  'kulfi': 'קולפי (גלידה הודית)',
  'mastic or lentisque': 'מסטיק (לנטיסק)',
  'fruits': 'פירות',
  'orris': 'איריס',
  // from Parfumo lists
  'blackcurrant': 'דומדמניות שחורות',
  'elemi resin': 'שרף אלמי',
  'woods': 'עצים',
  'american cedar': 'ארז אמריקאי',
  'brazilian tonka bean absolute': 'פול טונקה ברזילאי (אבסולוט)',
  'nagarmotha': 'נגרמוטה',
  'dry woods': 'עצים יבשים',
  'gaiac wood': 'עץ גואיאק',
  'spices': 'תבלינים',
  'juniper berry': 'גרגר ערער',
  'provençal lavender': 'לבנדר פרובנסלי',
  'liquorice': 'ליקריץ',
  'amber notes': 'תווי ענבר',
  'sapote': 'סאפוטה',
  'woodland strawberry': 'תות בר',
  'blond woods': 'עצים בהירים',
  'bitter orange leaf': 'עלה תפוז מר',
  'iris tingitana absolute': 'איריס טינגיטנה (אבסולוט)',
  'bourbon vetiver': 'ווטיבר בורבון',
  'cistus': 'ציסטוס',
  'bourbon vanilla absolute': 'וניל בורבון (אבסולוט)',
  'royal ann cherry': 'דובדבן רויאל אן',
  'tonka bean absolute': 'פול טונקה (אבסולוט)',
  'labdanum absolute': 'לבדנום (אבסולוט)',
  'vanilla absolute': 'וניל (אבסולוט)',
  'martinique rum': 'רום ממרטיניק',
  'thai oud': 'עוּד תאילנדי',
  'key lime': 'ליים קי',
  'coconut water': 'מי קוקוס',
  'white blossoms': 'פריחה לבנה',
  'pimento': 'פימנטו',
  'bergamot leaf': 'עלה ברגמוט',
  'iris aldehyde': 'איריס אלדהידי',
  'moroccan orris butter': 'חמאת איריס מרוקאית',
  'provençal clary sage': 'מרווה סקלארי פרובנסלית',
  'indian tuberose absolute': 'טוברוז הודי (אבסולוט)',
  'french iris pallida': 'איריס פלידה צרפתי',
  'grasse rose absolute': 'ורד מגראס (אבסולוט)',
  'indian jasminum grandiflorum': 'יסמין גרנדיפלורום הודי',
  'rose absolute': 'ורד (אבסולוט)',
  'rose water': 'מי ורדים',
  'egyptian jasminum grandiflorum absolute': 'יסמין גרנדיפלורום מצרי (אבסולוט)',
  'jasmine sambac absolute': 'יסמין סמבק (אבסולוט)',
  'ambrettolide': 'אמברטוליד',
  'moxalone®': 'מוקסלון',
  'sylkolide™': 'סילקוליד',
  'texas cedar': 'ארז טקסני',
  'orange blossom absolute': 'פריחת תפוז (אבסולוט)',
  'cade juniper': 'ערער קייד',
  'primofiore lemon': 'לימון פרימופיורה',
  'rum absolute': 'רום (אבסולוט)',
  'java vetiver': 'ווטיבר ג׳אווה',
  'tobacco absolute': 'טבק (אבסולוט)',
  'water jasmine': 'יסמין מים',
  'geranium absolute': 'גרניום (אבסולוט)',
  'maté absolute': 'מאטה (אבסולוט)',
  'orris concrete': 'איריס (קונקרט)',
  'cassia': 'קסיה',
  'blue ginger': 'ג׳ינג׳ר כחול',
  'evernyl': 'אוורניל',
  'pomarose®': 'פומרוז',
  'mugwort': 'לענה',
  'resins': 'שרפים',
  'ambrox': 'אמברוקס',
  'grasse jasmine': 'יסמין מגראס',
  'cypriol': 'סיפריול',
  'ice accord': 'אקורד קרח',
  'acajou wood': 'עץ מהגוני',
  'akigalawood®': 'אקיגלווד',
  'coriander seed': 'גרגרי כוסברה',
  'granny smith apple': 'תפוח גרני סמית׳',
  'scotch whisky absolute': 'ויסקי סקוטי (אבסולוט)',
  'italian iris concrete': 'איריס איטלקי (קונקרט)',
  'madagascan ginger': 'ג׳ינג׳ר מדגסקרי',
  'namibian myrrh': 'מור נמיבי',
  'ambrette seed': 'גרעיני אמברט',
  'salted vanilla': 'וניל מלוח',
  'kahili ginger': 'ג׳ינג׳ר קהילי',
  'amyl salicylate': 'אמיל סליצילט',
  'cetalox': 'סטלוקס',
  'helvetolide': 'הלבטוליד',
  'tonka': 'טונקה',
  'mocha': 'מוקה',
  'plum blossom': 'פריחת שזיף',
  'immortelle': 'אלמוות (אימורטל)',
  'liquor': 'ליקר',
  'carrot seeds': 'זרעי גזר',
  'mate': 'מאטה',
};

// Place and variety words that Fragrantica puts in front of a note ("Moroccan Jasmine",
// "Haitian Vetiver"). Used when the full name is not in the list above.
export const NOTE_ADJECTIVES_HE: Record<string, string> = {
  'moroccan': 'מרוקאי',
  'turkish': 'טורקי',
  'bulgarian': 'בולגרי',
  'indonesian': 'אינדונזי',
  'haitian': 'האיטי',
  'madagascar': 'ממדגסקר',
  'tahitian': 'טהיטי',
  'egyptian': 'מצרי',
  'indian': 'הודי',
  'mexican': 'מקסיקני',
  'italian': 'איטלקי',
  'sicilian': 'סיציליאני',
  'calabrian': 'קלבריאני',
  'brazilian': 'ברזילאי',
  'australian': 'אוסטרלי',
  'chinese': 'סיני',
  'japanese': 'יפני',
  'french': 'צרפתי',
  'virginian': 'וירג׳יני',
  'atlas': 'אטלס',
  'siamese': 'סיאמי',
  'mysore': 'מייסור',
  'cambodian': 'קמבודי',
  'laotian': 'לאוטי',
  'ceylon': 'ציילוני',
  'javanese': 'ג׳אוואני',
  'russian': 'רוסי',
  'spanish': 'ספרדי',
  'tunisian': 'תוניסאי',
  'persian': 'פרסי',
  'arabian': 'ערבי',
  'omani': 'עומאני',
  'yemeni': 'תימני',
  'sri lankan': 'סרי לנקי',
  'south african': 'דרום אפריקאי',
  'african': 'אפריקאי',
  'white': 'לבן',
  'black': 'שחור',
  'red': 'אדום',
  'pink': 'ורוד',
  'green': 'ירוק',
  'wild': 'בר',
  'fresh': 'טרי',
  'dry': 'יבש',
  'sweet': 'מתוק',
  'creamy': 'קרמי',
  'smoky': 'מעושן',
  'bitter': 'מר',
};

// Hebrew names of the "main accords" (the big scent families of a fragrance), lower case.
export const ACCORDS_HE: Record<string, string> = {
  'citrus': 'הדרי',
  'woody': 'עצי',
  'fresh': 'רענן',
  'fresh spicy': 'תבליני רענן',
  'warm spicy': 'תבליני חם',
  'soft spicy': 'תבליני עדין',
  'spicy': 'תבליני',
  'sweet': 'מתוק',
  'vanilla': 'וניל',
  'amber': 'ענברי',
  'powdery': 'אבקתי',
  'aromatic': 'ארומטי',
  'white floral': 'פרחי לבן',
  'yellow floral': 'פרחי צהוב',
  'floral': 'פרחי',
  'fruity': 'פירותי',
  'musky': 'מושקי',
  'earthy': 'אדמתי',
  'leather': 'עור',
  'smoky': 'מעושן',
  'tobacco': 'טבק',
  'rose': 'ורד',
  'balsamic': 'בלסמי',
  'oud': 'עוּד',
  'green': 'ירוק',
  'lactonic': 'חלבי',
  'cacao': 'קקאו',
  'almond': 'שקד',
  'tuberose': 'טוברוז',
  'patchouli': 'פצ׳ולי',
  'aquatic': 'ימי',
  'marine': 'ימי',
  'ozonic': 'אוזוני',
  'mineral': 'מינרלי',
  'coconut': 'קוקוס',
  'honey': 'דבש',
  'coffee': 'קפה',
  'caramel': 'קרמל',
  'lavender': 'לבנדר',
  'iris': 'איריס',
  'animalic': 'חייתי',
  'cinnamon': 'קינמון',
  'rum': 'רום',
  'salty': 'מלוח',
  'metallic': 'מתכתי',
  'terpenic': 'טרפני',
  'herbal': 'עשבי תיבול',
  'tropical': 'טרופי',
  'gourmand': 'גורמה',
  'creamy': 'קרמי',
  'sour': 'חמצמץ',
  'soapy': 'סבוני',
  'chocolate': 'שוקולד',
  'cherry': 'דובדבן',
  'coumarin': 'קומרין',
  'nutty': 'אגוזי',
  'conifer': 'מחטני',
  'mossy': 'טחבי',
  'violet': 'סיגלית',
  'sand': 'חולי',
  'wine': 'יין',
  'alcohol': 'אלכוהולי',
  'beeswax': 'שעוות דבורים',
  'cool spicy': 'תבליני קריר',
  'anis': 'אניס',
  'aldehydic': 'אלדהידי',
  'ozonic-marine': 'ימי אוזוני',
  'rubber': 'גומי',
  'camphor': 'קמפור',
  'bitter': 'מר',
  'smoke': 'עשן',
  'plastic': 'פלסטיק',
  'fragrant': 'ריחני',
  'cannabis': 'קנאביס',
  'clean': 'נקי',
  'sugary': 'סוכרי',
  'fruity-sweet': 'פירותי מתוק',
  'oriental': 'מזרחי',
  'synthetic': 'סינתטי',
  'leathery': 'עורי',
  'resinous': 'שרפי',
  'fougère': 'פוז׳ר',
};
